name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey Welcome to portfolioshop🌟. Congratulations on your first issue. We'll figure out something about it soon."
        pr-message: "Hi 🙌. Thanks for your contribution. Please make sure you've followed the contribution guidelines."
