name: Lighthouse CI
on: 
  pull_request:
    branches: 
      - master
jobs:
   lighthouse:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4

       - name: Setup node
         uses: actions/setup-node@v3
         with:
           node-version: "14.x"

       - name: Start MongoDB
         uses: supercharge/mongodb-github-action@v1.10.0
         with:
          mongodb-version: 4.0

       - name: Setup
         run: |
          . setup.sh
          npm install -g @lhci/cli

       - name: Build web app
         run: npx swa build
       
       - name: LighthouseCI
         run: lhci autorun
      
       - name: upload results as artifacts
         uses: actions/upload-artifact@v3
         with:
          name: lighthouse-results
          path: .lighthouseci
