name: Lighthouse CI
on: 
  pull_request:
    branches: 
      - master
jobs:
   lighthouse:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: Setup node
         uses: actions/setup-node@v1
         with:
           node-version: "14.x"
       - name: Start MongoDB
         uses: supercharge/mongodb-github-action@1.8.0
         with:
          mongodb-version: 4.0

       - name: Setup
         run: . setup.sh

       - name: LighthouseCI
         run: |
          npm install -g @lhci/cli@0.8.x
          npm install -g azure-functions-core-tools
          lhci autorun
