name: Lighthouse CI
on: 
  pull_request:
    branches: 
      - master
jobs:
   lighthouse:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: Setup node
         uses: actions/setup-node@v1
         with:
           node-version: "14.x"
           
       - name: Start MongoDB
         uses: supercharge/mongodb-github-action@1.8.0
         with:
          mongodb-version: 4.0

       - name: Setup
         run: |
          . setup.sh
          npm install -g @lhci/cli

       - name: 
         run: npx swa build
       
       - name: LighthouseCI
         run: lhci autorun
