name: Lighthouse CI
on: 
  pull_request:
    branches: 
      - master
jobs:
   lighthouse:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: Setup node
         uses: actions/setup-node@v1
         with:
           node-version: "14.x"

       - name: Install
         run: npm run dev-install

       - name: LighthouseCI
         run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun
